---
- name: Update banner message
  hosts: cisco
  connection: network_cli
  gather_facts: no

  vars:
    # multine banners need to use ios_banner - otherwise it fails - at least until now :-) 
    #banner_message:  | 
    #  ^Property of FinTech Inc.
    #  No unauthorized access
    #  Violators will be prosecuted^
    banner_message:  This is a single line banner
  tasks:

  - name: "Update banner message to {{ banner_message }}"
    ios_config:
      lines:
        "banner motd % {{ banner_message }} %"

